#!/usr/bin/python
# -*- coding: utf-8 -*-

from pyremgit import pyremgit
import sys, os

p = pyremgit()
if sys.argv.__len__()>=2:
	if sys.argv[1]=='connect':
		if sys.argv.__len__()>=3:
			p.connect(sys.argv[2])
		else:
			print 'missing argument : server'
			p.help__()
	elif sys.argv[1]=='cmd':
		if sys.argv.__len__()>=3:
			if sys.argv.__len__()>=4:
				x = 3
				cmd = []
				while x <= (sys.argv.__len__()-1):
					if os.path.isfile(sys.argv[x]):
						for f in open(sys.argv[x]):
							cmd.append(f)
					else:
						cmd.append(sys.argv[x])
					x = x+1
				p.cmd(sys.argv[2], cmd)
			else:
				print 'missing argument : commands'
				p.help__()
		else:
			print 'missing argument : server'
			p.help__()
	else:
		print 'unknown command'
		p.help__()

else:
	p.help__()