#!/usr/bin/python
# -*- coding: utf-8 -*-

from pyremogit import pyremogit
import sys, os

p = pyremogit()
if sys.argv.__len__()>=2:
	if sys.argv[1]=='connect':
		if sys.argv.__len__()>=3:
			p.connect(sys.argv[2])
		else:
			print 'missing argument : server'
			p.help__()
	elif sys.argv[1]=='cmd':
		if sys.argv.__len__()>=3:
			if sys.argv.__len__()>=4:
				x = 3
				cmd = []
				while x <= (sys.argv.__len__()-1):
					if os.path.isfile(sys.argv[x]):
						for f in open(sys.argv[x]):
							cmd.append(f)
					else:
						cmd.append(sys.argv[x])
					x += 1
				p.cmd(sys.argv[2], cmd)
			else:
				print 'missing argument : commands'
				p.help__()
		else:
			print 'missing argument : server'
			p.help__()
	elif sys.argv[1] == 'shell':
		p.shell(sys.argv[2])
	elif sys.argv[1]=='put':
		if sys.argv.__len__()>=3:
			x = 3
			files = {}
			while x <= (sys.argv.__len__()-1):
				f = sys.argv[x].split('=>')
				files[f[0]] = f[1]
				x += 1
			p.put(sys.argv[2], files)
		else:
			print 'missing argument : "/path/to/local/file=>/path/to/remote/file"'
			p.help__()
	elif sys.argv[1]=='get':
		if sys.argv.__len__()>=3:
			x = 3
			files = {}
			while x <= (sys.argv.__len__()-1):
				f = sys.argv[x].split('=>')
				files[f[0]] = f[1]
				x += 1
			p.get(sys.argv[2], files)
		else:
			print 'missing argument : "/path/to/remote/file=>/path/to/local/file"'
			p.help__()
	elif sys.argv[1]=='pull':
		if sys.argv.__len__()>=3:
			p.pull(sys.argv[2])
		else:
			print 'missing argument : remote:branch or configured pull key'
			p.help__()
	elif sys.argv[1]=='push':
		if sys.argv.__len__()>=3:
			p.push(sys.argv[2])
		else:
			print 'missing argument : remote:branch or configured pull key'
			p.help__()
	elif sys.argv[1]=='commit':
		if sys.argv.__len__()>=3:
			if sys.argv.__len__()>=4:
				mess = sys.argv[3]
			else:
				mess = ''
			p.commit(sys.argv[2], mess)
		else:
			print 'missing argument : commit flag'
			p.help__()
	elif sys.argv[1]=='pullsh':
		if sys.argv.__len__()>=3:
			p.commit(sys.argv[2], '')
			p.pull(sys.argv[3])
			p.push(sys.argv[3])
		else:
			print 'missing argument : configured pull/push key'
			p.help__()
	else:
		print 'unknown command'
		p.help__()

else:
	p.help__()